import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import localFont from 'next/font/local';

const yekan = localFont({
  src: '../public/fonts/yekan/woff2/IRANYekanWebMedium.woff2',
  variable: '--font-yekan',
});
export const metadata: Metadata = {
  title: "Diko Admin Panel",
  description: "Generated by Ahmad Moradi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="fa" dir="rtl" className={yekan.variable}>
      <body className="font-yekan">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
